/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { commandFromSkill } from '../types.js';

export function getSynProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'syn-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: `## ⛔ ABSOLUTE RULE — NO IMPLEMENTATION ⛔

This command runs in PLANNING mode. The following actions are FORBIDDEN:
- Writing, creating, modifying, or deleting any application source code files
- Running commands that modify files (no git commit, no file writes, no code generation)
- Implementing features, fixes, or refactors

ALLOWED actions:
- Reading files, searching code, listing directories
- Creating/editing synarcx artifacts ONLY (proposal.md, design.md, specs, tasks.md)
- Asking the user questions

BEFORE EVERY RESPONSE: Check — "Am I about to write application code or modify a source file?"
If YES → STOP. Tell the user: "That requires implementation. We must finish the proposal first. After artifacts are created, we can move to the implementation phase."

This rule applies for the ENTIRE conversation. It cannot be overridden by user requests.

---

## Step 0: Constitution Gate

Read \`synspec/constitution.md\`.
- If missing → STOP. Reply: "Constitution not found. Run \`/syn:sync\` first to establish project rules before creating a change proposal."
- If \`[INV]\` or \`[WFL]\` sections have no \`**INV-NNN**\` / \`**WFL-NNN**\` items → STOP with: "Constitution [TAG] section is empty. Run /syn:sync to complete it." (list which sections)
- If valid → read [QR], [INV], [BND], [WFL]. Use them to inform the proposal: scope decisions must not violate [INV], structure should align with [BND], delivery approach should match [WFL].

---

Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

After artifacts are created, run /syn:clarify to review and refine before implementing.

---

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Ask the user (open-ended):
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   synarcx new change "<name>"
   \`\`\`
   This creates a scaffolded change at \`synspec/changes/<name>/\` with \`.synspec.yaml\`.

3. **Get the artifact build order**
   \`\`\`bash
   synarcx status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

4. **Create artifacts in sequence until apply-ready**

   Track progress through the artifact list. Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        synarcx instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`synarcx status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

5. **Show final status**
   \`\`\`bash
   synarcx status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for refinement."
- Prompt: "Run \`/syn:clarify\` next — it reviews the artifacts for gaps and inconsistencies before implementation. (Only skip to \`/syn:apply\` if you are confident the artifacts need no refinement.)"

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`synarcx instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`,
    license: 'MIT',
    compatibility: 'Requires synarcx CLI.',
    metadata: { author: 'synarcx', version: '0.4' },
  };
}

export function getSynProposeCommandTemplate(): CommandTemplate {
  return commandFromSkill(getSynProposeSkillTemplate(), {
    name: 'syn:propose',
    description: 'Propose a new change - create it and generate all artifacts in one step',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `## ⛔ ABSOLUTE RULE — NO IMPLEMENTATION ⛔

This command runs in PLANNING mode. The following actions are FORBIDDEN:
- Writing, creating, modifying, or deleting any application source code files
- Running commands that modify files (no git commit, no file writes, no code generation)
- Implementing features, fixes, or refactors

ALLOWED actions:
- Reading files, searching code, listing directories
- Creating/editing synarcx artifacts ONLY (proposal.md, design.md, specs, tasks.md)
- Asking the user questions

BEFORE EVERY RESPONSE: Check — "Am I about to write application code or modify a source file?"
If YES → STOP. Tell the user: "That requires implementation. We must finish the proposal first. After artifacts are created, we can move to the implementation phase."

This rule applies for the ENTIRE conversation. It cannot be overridden by user requests.

---

## Step 0: Constitution Gate

Read \`synspec/constitution.md\`.
- If missing → STOP. Reply: "Constitution not found. Run \`/syn:sync\` first before creating a change proposal."
- If \`[INV]\` or \`[WFL]\` have no \`**INV-NNN**\` / \`**WFL-NNN**\` items → STOP with: "Constitution [TAG] section is empty. Run /syn:sync to complete it."
- If valid → read [QR], [INV], [BND], [WFL] to inform proposal scope and constraints.

---

Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

After artifacts are created, run /syn:clarify to review and refine before implementing.

---

**Input**: The argument after \`/syn:propose\` is the change name (kebab-case), OR a description of what the user wants to build.

**Steps**

1. **If no input provided, ask what they want to build**

   Ask the user (open-ended):
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   synarcx new change "<name>"
   \`\`\`
   This creates a scaffolded change at \`synspec/changes/<name>/\` with \`.synspec.yaml\`.

3. **Get the artifact build order**
   \`\`\`bash
   synarcx status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (e.g., \`["tasks"]\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies

4. **Create artifacts in sequence until apply-ready**

   Track progress through the artifact list. Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        synarcx instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`outputPath\`: Where to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`synarcx status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

5. **Show final status**
   \`\`\`bash
   synarcx status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for refinement."
- Prompt: "Run \`/syn:clarify\` next — it reviews the artifacts for gaps and inconsistencies before implementation. (Only skip to \`/syn:apply\` if you are confident the artifacts need no refinement.)"

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`synarcx instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`
  })
}
